include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test

pylint:
  image: python:3.7
  script:
    - pip install -r requirements.txt
    - pip install pylint pylint-junit
    - pylint --fail_under 9.5 --output-format=pylint_junit.JUnitReporter gitlab_group_fork.py | tee rspec.xml
  artifacts:
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
    when: always
  allow_failure: true
  
